{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hb-svc-notification.fullname" . }}-rolebinding
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hb-svc-notification.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ include "hb-svc-notification.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
