spring:
  cloud:
    config:
      enabled: false

  kafka:
    bootstrap-servers: bt-kafka-helm.bt.svc.cluster.local:8010
    consumer:
      group-id: bh-notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


kafka:
  topic:
    hb-post-event: hb-post-create-update-event
  group_id: bh-notification-group
  max_retries: 3

fierhub:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJhbnkiLCJuYmYiOjE3ODkwNjI4NzQsImV4cCI6MTgyMjMyODk0MCwiaWF0IjoxNzg5MDYyODc0LCJpc3MiOiJpbmZvX2JvdHRvbWhhbGZfaW4iLCJhdWQiOiJmaWVyaHViLXNlcnZpY2VzIn0.jfAObA3aHoD3ap4VEad-gqKaik7P96R1zuvrpNw_cb0_tid20_cid=120