# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven - Production
      run: mvn clean install

    - name: Get Short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: bottomhalflimited/hb-svc-notification
        tags: latest,${{ steps.vars.outputs.sha_short }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: SSH to Remote server and deploy
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    - name: Apply new changes
      run: |
        helm template hb-svc-notification helm \
          --set image.tag=${{ steps.vars.outputs.sha_short }} \
          -n hb | ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            microk8s kubectl apply -f -
            
            if microk8s kubectl get deployment notification-service -n hb > /dev/null 2>&1; then
              microk8s kubectl rollout restart deployment notification-service -n hb
            fi
          "

    - name: cleanup
      run: |
        echo "Cleaning up SSH credentials"
        rm -rf ~/.ssh